### ISSUE TITLE
UnexpectedText should carry the index of the unexpectation

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/cpp_demangle#21]
This would be the `tail.index()` or `input.index()` where we first saw some unexpected text.

**Comment by fitzgen** [comment]
Actually this is not really worth it. Its not like people are writing C++ symbols themselves.

**Comment by jimblandy** [comment]
I agree. It might be useful in the rare circumstance in which one is debugging bad mangling, but other than that nobody cares.
