### ISSUE TITLE
MSVC demangling

### ISSUE THREAD

**Issue by luser** [fitzgen/cpp_demangle#36]
I don't know if it's in scope, but it would be nice to have demangling for [MSVC C++ names](https://msdn.microsoft.com/en-us/library/56h2zst2.aspxurl) as well. It's not officially documented, but there is a fair bit of info out there about it:
https://en.wikiversity.org/wiki/Visual_C%2B%2B_name_mangling
http://www.kegel.com/mangle.html

Wine has an (LGPL) implementation of undname:
http://source.winehq.org/git/wine.git/blob/HEAD:/dlls/msvcrt/undname.c

clang has support for generating MSVC-compatible mangled names:
https://github.com/llvm-mirror/clang/blob/966fedc25951ad35732cb9e175decf271dc3ed09/lib/AST/MicrosoftMangle.cpp

and it has some tests for it as well:
https://github.com/llvm-mirror/clang/blob/a0badfbffbee71c2c757d580fc852d2124dadc5a/test/CodeGenCXX/mangle-ms.cpp

**Comment by fitzgen** [comment]
Hi Ted! Sorry for the delayed response, I've been on vacation with intermittent connectivity.

How much code sharing do you think we could have between Itanitum and MSVC demangling? If there is a sizable amount of code to share, then I would be in favor of supporting it in this crate. If there isn't, then I think it would be better to implement it in a separate crate, and then make an umbrella crate for demangling anything. In fact, I want to make such a crate anyways, that tries to demangle the given symbol as if it were Rust, or Itanium, or MSVC, or ...

Without having followed any of those links, my intuition is that there probably isn't much to share, and MSVC demangling should be its own crate. Do you have the same intuition? Looking at the links now...

**Comment by fitzgen** [comment]
Hmm.... Looks like MSVC also uses back references and some sort of substitution table.

**Comment by fitzgen** [comment]
cc @lifthrasiir, do you have an intuition about how much code could be shared between demangling MSVC and Itanium symbols?

**Comment by luser** [comment]
I suspect there wouldn't be any real shared code. That is totally OK! We can just make an msvc-demangle crate for that, and another crate that does arbitrary symbol demangling.

**Comment by jrmuizel** [comment]
There's a crate for this now: https://crates.io/crates/msvc-demangler
