### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fithisux** [fitzgen/cpp_demangle#55]
What is the license of this software? Is it possible to have it in the GPL flavor?

**Comment by fitzgen** [comment]
It is currently dual licensed as either MIT or Apache 2.0. I would be happy to tri-license it with GPL as well (assuming that is even possible?) if @JimBlandy is OK with that as well.

Also, I just realized we only have the license info in `Cargo.toml` and should probably add their text to the repo properly.

**Comment by emaste** [comment]
It's already GPL compatible, so I don't see that triple-licensing it brings any real benefit.

**Comment by binarycrusader** [comment]
Thanks for fixing this, I just saw the blog post today and was excited about using this for a new project, but can't until the license gets formally added.  I'd strongly recommend a copyright notice on each file that references a LICENSE.txt in the root of your project.  Thanks!

(BTW, for the record, MIT/Apache 2.0 greatly appreciated.)

**Comment by fitzgen** [comment]
> It's already GPL compatible, so I don't see that triple-licensing it brings any real benefit.

It isn't 100% clear to me either, other than potential political reasons for some project wanting to only use GPL (even though MIT should be linkable) perhaps. @fithisux, could expand here?

That said, if it's helpful, I'm happy to do it.
