### ISSUE TITLE
src/bin/cppfilt.rs should have --help and --version

### ISSUE THREAD

**Issue by tromey** [fitzgen/cpp_demangle#70]
c++filt should accept `--help` and `--version` flags and DTRT.

**Comment by fitzgen** [comment]
We should probably use `clap` for this.

This would be a good first bug to hack on if anyone is interested. I can mentor and answer any questions that arise :)

**Comment by mclark4386** [comment]
Hopefully that's an acceptable patch this is my first PR for a rust project and my second day using the language, so please let me know if there is anything I should do differently or could do better! Thanks!
