### ISSUE TITLE
Regression from 0.2.0, symbol can't be demangled

### ISSUE THREAD

**Issue by alexcrichton** [fitzgen/cpp_demangle#73]
Discovered through the test suite of [backtrace-rs](https://github.com/alexcrichton/backtrace-rs) it looks like the symbol `_ZN5space20templated_trampolineIPFvvEEEvT_` is no longer demangled as `void space::templated_trampoline<void (*)()>(void (*)())` I believe?

**Comment by fitzgen** [comment]
Thanks for the bug report!

**Comment by fitzgen** [comment]
Fixed in 0.2.6
