### ISSUE TITLE
Invalid rerun dependency path in build.rs

### ISSUE THREAD

**Issue by crumblingstatue** [fitzgen/cpp_demangle#79]
[Here](https://github.com/fitzgen/cpp_demangle/blob/82d942a2896300c54a180cea97a26267ccd037aa/build.rs#L23):

`println!("cargo:rerun-if-changed=in/*");`

Globs are not expanded by Cargo, they are interpreted literally, meaning this is likely referring to a nonexistent location.

Ref https://github.com/rust-lang/cargo/issues/4076

**Comment by YaLTeR** [comment]
This results in constant recompiling of `error_chain` (which depends on `backtrace` which depends on `cpp_demangle`), which is extremely annoying.

**Comment by fitzgen** [comment]
Thanks for catching this! Fix on the way.

**Comment by fitzgen** [comment]
Fixed and published 0.2.2.
