### ISSUE TITLE
High build time because of clap in the dependencies.

### ISSUE THREAD

**Issue by pftbest** [fitzgen/cpp_demangle#82]
Hello, I am using `error-chain` crate, which depends on `backtrace` which in turn depends on this crate. So I am not using `cpp_demangle` directly, and I don't need the binaries it provides, but cargo still have to compile `clap` crate because it is listed in the dependencies. And it takes more than a minute to compile `clap` on my setup.

Is there some way to remove `clap` from the dependencies when this crate is used as a library?

cargo tree output:
```
└── error-chain v0.10.0
    └── backtrace v0.3.1
        ├── backtrace-sys v0.1.10
        │   └── libc v0.2.23
        ├── cfg-if v0.1.0
        ├── cpp_demangle v0.2.2
        │   ├── clap v2.24.2
        │   │   ├── ansi_term v0.9.0
        │   │   ├── atty v0.2.2
        │   │   │   └── libc v0.2.23 (*)
        │   │   ├── bitflags v0.8.2
        │   │   ├── strsim v0.6.0
        │   │   ├── term_size v0.3.0
        │   │   │   └── libc v0.2.23 (*)
        │   │   ├── unicode-segmentation v1.2.0
        │   │   ├── unicode-width v0.1.4
        │   │   └── vec_map v0.8.0
        │   └── fixedbitset v0.1.6
        ├── libc v0.2.23 (*)
        └── rustc-demangle v0.1.4
```

**Comment by pftbest** [comment]
Thanks!

**Comment by fitzgen** [comment]
See also https://github.com/alexcrichton/backtrace-rs/pull/51
