### ISSUE TITLE
implement mangling

### ISSUE THREAD

**Issue by fneddy** [fitzgen/cpp_demangle#90]
Would it be possible to use this vice-versa to mangle a cpp symbol name?

what I actually want to achieve:
  1. dlopen a cpp library
    ` let m = dlopen("libQt5Core.so", RTL_LAZY );`
  2. mangle a given c++ symbol 
    `let symbol = Symbol::fromName( "QString::fromUtf16(unsigend short const*, int)" );  `
    ` // symbol.magle()  -> "_ZN7QString9fromUtf16EPKti" `
 3. use dlsym to find function;
    ` let thecppfunc = dlsym(m, symbol.mangle());`
 4. be able to use the function from rust !

**Comment by fitzgen** [comment]
That is indeed a cool use case, but I think it is best served by another crate. There isn't much if any code that would be shared with this crate.
